### ISSUE TITLE
"qs" dependency needs to be updated

### ISSUE THREAD

**Issue by rastemoh** [gdaws/node-stomp#104]
NPM warns that the qs package has a vulnerability in the version that the node-stomp package is using and it should be updated. 
You may find more on this [here](https://www.npmjs.com/advisories/1469)

Is there any plans for updating that dependency to version 6 or above?

**Comment by gdaws** [comment]
Thanks for bringing this to my attention I'll update the dependency to its latest version.

**Comment by jwarchol** [comment]
WIll a new release be cut for this?
