### ISSUE TITLE
How to set message properties, example AMQ_SCHEDULED_DELAY 

### ISSUE THREAD

**Issue by sbansal6** [gdaws/node-stomp#16]
hi, how do i set AMQ_SCHEDULED_DELAY property of the message (this property delays the sending of the message, http://activemq.apache.org/delay-and-schedule-message-delivery.html

I am using the following code to send the message 

var channel = new stompit.ChannelFactory(connectionManager);
    channel.send(queue, messageText, function(error) {
        if (error) {
            var error = new Error('Cannot sendMessage: ' + messageText + ' : ' + error);
            callback(error);
        }
        else {
            console.log('Successfully sent message on queue ' + queue + ':' + messageText);
            callback()
        }

    });

**Comment by gdaws** [comment]
My assumption is ActiveMQ's stomp adapter accepts jms message properties as stomp headers, and your question is how to set headers in stompit. The first parameter of the channel send method can be passed a header object argument. Here's a code example:

    channel.send({
        'destination': queue,
        'AMQ_SCHEDULED_DELAY': delayNumber
    }, messageText, sentHandler);

**Comment by sbansal6** [comment]
@gdaws  :+1: Thanks a lot. it works .
