### ISSUE TITLE
connection timeout 

### ISSUE THREAD

**Issue by freegenie** [gdaws/node-stomp#18]
Hi, I'm not sure this is an issue so please take it as a simple question. I'm using your awesome library for a nodejs server that keeps listening on an AMQ queue. The client must keep listening for new messages so I'm not doing any `client.disconnect()` after `message.ack()`.
Everything works fine, but now and then I receive a 'connection timed out' error I don't know how to recover from. When that error happens, the server stops receiving messages.

I was thinking to reissue the `stompit.connect` command when that happens but I wonder if there's any better way to handle such errors. 

Thanks.

**Comment by gdaws** [comment]
On an error event the client enters a dead state and cannot be reused over a new socket. To recover you must reissue a `stompit.connect` call and start again with a new client object.

You may want to consider using the library's Channel API. It's an alternative to using the Client API and it provides automatic connection management and handles connection errors for you. Here's a partial code example to show usage:

```
var connectionManager = new stompit.ConnectFailover();

connectionManager.addServer({
  'host': 'localhost',
  'port': 61613,
  'connectHeaders':{
    'host': '/',
    'login': 'username',
    'passcode': 'password',
    'heart-beat': '5000,5000'
  }
});

var channel = new stompit.Channel(connectionManager);

var subscribeHeaders = {
	'destination': '/queue/somewhere'
};

channel.subscribe(subscribeHeaders, function(error, message){
	
	if (error) {
		console.log(error);
		return;
	}
	
	// read message and then ack
});
```

The argument passed to `addServer` is the same argument you would pass to `stompit.connect`. The error argument passed to the subscribe callback is an Error object value after the connection manager has exhausted its connection attempts and it should be treated as a fatal error. The second parameter of ConnectFailover allows you to tweak the reconnect behaviour and how soon it gives up. The default setting allows unlimited reconnects.

**Comment by iravinandan** [comment]
Hi @gdaws , I am using the same snippet but after subscribe error reconnection is not happening. Anything I am missing?
