### ISSUE TITLE
Binary payload

### ISSUE THREAD

**Issue by ColorfullyMe** [gdaws/node-stomp#28]
```js
  var frame = client.send(sendHeaders);
  frame.write('hello');
  frame.end();
```
What will be the correct way to send Buffer instead of 'hello'?
It looks that `frame.write(Buffer('test'));` gets converted to string and then send?
Even setting headers like:
```
    var sendHeaders = {
        'destination': '/queue/test',
        'content-type': 'binary'
    };
```

**Comment by gdaws** [comment]
The buffer stays as a buffer throughout the write operation. What makes you think the buffer is converted to a string?

The Content-Type header doesn't affect the behaviour of frame write.

**Comment by ColorfullyMe** [comment]
@gdaws My bad. Thanks!
