### ISSUE TITLE
Process one message at a time

### ISSUE THREAD

**Issue by sbansal6** [gdaws/node-stomp#34]
Hi, i am using this library for past one year and very happy with it. The only thing i am not able to figure out is how does i constrain my subscriber to process one message at a time. 

In current code (below) , the subscriber starts processing all message at the same time. 

var subscribe = function (queueName) {
  var subscribeHeaders = { 'destination': '/queue/' + queueName, 'ack': 'auto'};
  var connectionManager = new stompit.ConnectFailover(server);
  var channel = new stompit.ChannelFactory(connectionManager);
  logger.log('info', 'subscriber listening on queue ' + queueName);
  channel.subscribe(subscribeHeaders, function (error, message) {
    if (error) {
      logger.log('fireError', 'subscribe error ' + error.message);
      return;
    }
    message.readString('utf-8', function (error, body) {
      if (error) {
        logger.log('fireError', 'read message error ' + error.message);
        return;
      }
      logger.log('info', 'received message: ' + body);
      message.ack();
      processMessage(JSON.parse(body));
    });
  });
};

**Comment by chubbsnes65** [comment]
Hi, I'm trying to  implement this in a connectFailover but I'm still recreiving all messages at  the same time, any advice on this?, thanks in advance.

Btw, we're happy using  this library thanks 👍
