### ISSUE TITLE
Receive binary content

### ISSUE THREAD

**Issue by RicardoRFaria** [gdaws/node-stomp#35]
Hi, I need to receive from stomp server a message with binary payload but I only found functions `readString` and `readEmptyBody` at `IncomingFrame`.
This lib supports this kind of message? If yes, is possible convert the stream to node Buffer?

**Comment by gdaws** [comment]
Yes it's possible to receive a binary payload. `IncomingFrame` implements [stream.Readable](https://nodejs.org/api/stream.html#stream_class_stream_readable) interface; use the `readable.read([size])` method to read and return a chunk of the payload as a Buffer object. To get the entire payload as a single buffer, concatenate each chunk buffer until the `end` event is emitted on the message.
