### ISSUE TITLE
EventEmitter memory leak with ack message

### ISSUE THREAD

**Issue by jcreigno** [gdaws/node-stomp#37]
When I set ack mode to `client-individual` with a call back `message.ack` I get the following error :

```
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Client.addListener (events.js:239:17)
    at Client.sendFrame (/home/jerome/public/node-stomp/lib/Client.js:78:12)
    at Subscription._sendAck (/home/jerome/public/node-stomp/lib/client/Subscription.js:106:18)
    at IncomingFrame.ack (/home/jerome/public/node-stomp/lib/client/Subscription.js:135:12)
    at IncomingFrame.<anonymous> (/home/jerome/public/node-stomp/test/Client.js:529:33)
    at emitNone (events.js:72:20)
    at IncomingFrame.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```
I'm using Node v4.2.4 on linux.

I can create a pull request with a test case to reproduce this issue, though I'm not sure how to fix it.

Jerome

**Comment by gdaws** [comment]
When I run `npm test` on stompit while having Node 4.2.4 installed I don't see a warning message. Are you running a modified test?

The memory leak detection is probably a false positive. The listener added at `Client.js:78` is later removed by the receipt handler.

Sending 11 or more ACK messages at once, and supplying a callback argument in each `message.ack` call will cause a memory leak detection warning.

**Comment by jcreigno** [comment]
Yes I've changed the Client test file on my clone to reproduce the warning : 1a7a633be90b505e9fda8749a4c42af181fdfb7b

Indeed it might not be a memory leak but I find it a little annoying to have this warning popping out just by adding a callback arg on `message.ack`.

**Comment by gdaws** [comment]
Each callback requires its own internal error listener adding to the client and this unavoidably creates the possibility of raising a memory leak warning. If you continue to use `message.ack(callback)` then you should disable the memory leak warning with `client.setMaxListeners(Infinity)`.

In master there's a commit 6968e95d0d55c0b528d850cb73a024b4515b99b8 to extend the behaviour of message.ack function to either accept a callback or a sendOptions object (has the same options as used in Client.send). Using `message.ack(sendOptions)` is a workaround to the warning issue and it doesn't require disabling the max-listeners warning.

Example code:
```js
message.ack({onReceipt: function() {

});
```
Note that the onReceipt callback doesn't have an error parameter. The callback won't be called on client error.

**Comment by jcreigno** [comment]
Ok thanks, I'll use `message.ack(sendOptions)` form as it will not require to change maxlisteners.
You can close this issue.

Thanks again for your help and your work on this module.

**Comment by sbansal6** [comment]
Hi gdaws, i am seeing the same error :- 

(node) warning: possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:239:17)
    at Processor.processOperation (/home/marin/feature/pubsub/processor.js:174:13)
    at processMessage (/home/marin/feature/pubsub/subscriber.js:69:14)
    at /home/marin/feature/pubsub/subscriber.js:53:7
    at IncomingFrame.<anonymous> (/home/marin/feature/node_modules/stompit/lib/IncomingFrameStream.js:461:5)
    at emitNone (events.js:72:20)
    at IncomingFrame.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickDomainCallback (node.js:394:17)

**Comment by sbansal6** [comment]
@gdaws :- here is my code. 

var subscribe = function (queueName) {
  var subscribeHeaders = {
    'destination': '/queue/' + queueName,
    'activemq.prefetchSize' : 1,
    'ack':'client'
  };

  var connectionManager = new stompit.ConnectFailover(sdk.labsmsgbus.activeMqCluster(labsMqBrokerConfig));
  var channel = new stompit.ChannelFactory(connectionManager);
  logger.log('info', 'subscriber listening on queue ' + queueName);

  channel.subscribe(subscribeHeaders, synchronisedHandler(function (error, message, next) {
    if (error) {
      logger.log('fireError', 'subscribe error ' + error.message);
      return;
    }
    message.readString('utf-8', function (error, body) {
      if (error) {
        logger.log('fireError', 'read message error ' + error.message);
        return;
      }

      logger.log('info', 'received message: ' + body);
      message.ack();
      processMessage(JSON.parse(body), function() {
        next();
      });

      // Exit process on uncaught exceptions, forever will restart the subscriber
      process.on('uncaughtExceptionOccurred',function(){
        setTimeout(function(){process.exit(0);},1000)
      })

    });
  }));

};

var processMessage = function (jsonMessage,processMessageCb) {
  var newProcess = new processor();
  newProcess.processOperation(jsonMessage, function (err) {
    if (err) {
      logger.log('error', 'Failed message with id: ' + jsonMessage._id);
      processMessageCb(err)
    } else {
      logger.log('info', 'Subscriber completed processing message id: ' + jsonMessage._id);
      processMessageCb();
    }
  });
};

function synchronisedHandler(callback) {
  var processing = false;
  var nextMessage = null;
  var next = function() {
    if (nextMessage === null) {
      processing = false;
      return;
    }
    var currentMessage = nextMessage;
    nextMessage = null;
    callback.apply(null, currentMessage);
  };

  return function(error, message) {
    if (processing) {
      nextMessage = [error, message, next];
      return;
    }
    processing = true;
    callback(error, message, next);
  }
}

**Comment by gdaws** [comment]
@sbansal6 the error originates in your code. You're adding a new event listener for an uncaught exception each time a message is read and I can't see where these listeners are removed.

It looks like you've misplaced this code:
```
// Exit process on uncaught exceptions, forever will restart the subscriber
  process.on('uncaughtExceptionOccurred',function(){
    setTimeout(function(){process.exit(0);},1000)
  })
```

This should be called once in your application.

**Comment by sbansal6** [comment]
@gdaws thanks a lot.
