### ISSUE TITLE
Provide a way to specify connect headers like heart-beat and client-id along with failoverUri string

### ISSUE THREAD

**Issue by choudhary001** [gdaws/node-stomp#39]
I am using ActiveMQ and want to have a durable subscription for a topic. I need to specify client-id in connect headers along with activemq.subscriptionName in subscribe headers.

But with usage of failoveruri string as in below code I am not sure how to do that. I can use servers list but using failover uri string is cleaner and easier.  I would like to modify heart-beat header as well before connect.

Could you please help me here?

```
var stompit = require('stompit')
var reconnectOptions = {
    'maxReconnects': 100,
    'randomize'    : false
};

var connManager = new stompit.ConnectFailover("failover:stomp://host1:61613,stomp://host2:61613)", reconnectOptions);

```

**Comment by gdaws** [comment]
Connect headers can be set in the query string of the failover uri, like for example:

```
failover:stomp://host1:61613,stomp://host2:61613?connect[connectHeaders][client-id]=value&connect[connectHeaders][heart-beat]=value
```

These headers will apply to all servers in the ConnectFailover object.

If unique headers are required for each server connection and you still want to use failover uri strings then you must use the `addServer` method.

```js
connManager.addServer("failover:stomp://host1:61613?connect[connectHeaders][name]=value");
connManager.addServer("failover:stomp://host2:61613?connect[connectHeaders][name]=value");
```

**Comment by choudhary001** [comment]
It fails to parse this:

`"failover:(stomp://u-choudhab-phoenix-mqbroker-1.sd.com:61613?connect[connectHeaders][client-id]=test-consumer&connect[connectHeaders][heart-beat]=\'0,10000\',stomp://u-choudhab-phoenix-failovermqbroker-1.sd.com:61613?connect[connectHeaders][client-id]=test-consumer&connect[connectHeaders][heart-beat]=\'0,10000\')";`

**Comment by gdaws** [comment]
Try:

<code>"failover:(stomp://u-choudhab-phoenix-mqbroker-1.sd.com:61613,stomp://u-choudhab-phoenix-failovermqbroker-1.sd.com:61613)?connect[connectHeaders][client-id]=test-consumer&connect[connectHeaders][heart-beat]=0,10000"</code>

The query string goes after the server list.
