### ISSUE TITLE
How to handle/consume binary data 

### ISSUE THREAD

**Issue by choudhary001** [gdaws/node-stomp#46]
Hi,

I have requirement where my node consumer will be consuming binary data. I get below 'message' object on receiving binary data:
{"_readableState":{"objectMode":false,"highWaterMark":0,"buffer":[],"length":0,"pipes":null,"pipesCount":0,"flowing":null,"ended":false,"endEmitted":false,"reading":false,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"defaultEncoding":"utf8","ranOut":false,"awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":null,"_events":{},"_eventsCount":1,"command":"MESSAGE","headers":{"content-length":10,"expires":"1463061403952","destination":"/topic/test.topic.0","subscription":"1","priority":"4","message-id":"ID:shakti01.hyd.deshaw.com-51570-1462974867310-1:1:1:1:28","timestamp":"1462975003952"},"ackType":"ACK"}

I am not sure how to consume binary data with this API. Could you please help

**Comment by gdaws** [comment]
The message object extends Node's stream.Readable class. 

I imagine plenty of resources can be found on the web that show how to handle binary data in Node.  Read the official documentation of Node's Buffer and stream.Readable classes.
