### ISSUE TITLE
How to unref

### ISSUE THREAD

**Issue by mlucool** [gdaws/node-stomp#47]
Hi,

How do I unref this so that it will not hold up my process just by being alive? Similar to https://nodejs.org/api/net.html#net_socket_unref but on the whole stompit layer (reconnects and all).

**Comment by gdaws** [comment]
Ensure the channel pool and all channels in use are closed. It's currently undocumented but the channel pool class has a close method which closes all of its owned channels and aborts pending reconnects.

If you're using the client class then call the disconnect method.

Stompit won't keep the process alive if it doesn't have any connections open.

**Comment by mlucool** [comment]
Thanks for the tip. For anyone else reading this you also need to call [abort](https://github.com/gdaws/node-stomp/blob/master/lib/ConnectFailover.js#L312). Maybe abort should also kill the client? Or a close method be added to ConnectFailover to call abort and kill the client if there is one. For now I was able to add my own close wrapper and got by. Thanks!
