### ISSUE TITLE
Best way to set a continuous consumer

### ISSUE THREAD

**Issue by dakairus** [gdaws/node-stomp#48]
Hi guys, I've being struggling a little bit understanding what is the best strategy for a task I got involved at my work. Currently I need to set a continuous consumer for a dedicated queue in one of our node js applications. I handled at the moment creating a connect fail over object and generating a channel passing the fail over object and then subscribing to the dedicated queue.

Works properly for about few hours, then suddenly I lost the connection with no errors and no reconnection attempt. My understand is that the connect fail over will perform reconnect and if not available will to a lookup in the list of servers that I provide in the build.

Is this the proper way to achieve the case I'm working on or is there any other recommendable option?. Currently I have to being restarting the server every 2 or 3 hours.

here a little example of what I'm doing, please correct if I'm wrong, I'm new into stomp servers:

```
MessageBussService.js
getConnectFailOverObject() {
    return new stompit.ConnectFailover(['server1','server2','server3'], {
      maxReconnects: 50,
      randomize: true,
      useExponentialBackOff: true
    });
  }

subscribe(connectFailOver, responseQueueName) {
    let channel = new stompit.Channel(connectFailOver, { alwaysConnected: true });

    channel.subscribe({
      destination: responseQueueName
    }, (err, message) => {
      if (err) return vApp.log.error(err);

      return app.eventEmitter.emit('MQ_EVENT_IN', message, message.headers);
    });
  }

ServerInit.js

MessageBusService.subscribe(MessageBusService.getConnectFailOverObject(), '/queue/DEDICATED_QUEUE');
```

**Comment by gdaws** [comment]
Your connect failover configuration is missing an option that could solve your connection issue. For long-lived connections it's advisable to use STOMP heart-beat as it helps to detect dead connections. It's important to use it for a connection used solely for consuming messages as a dead connection is not likely to be detected if the consumer is just waiting silently to receive data.

Here is a modification to part of your code to show how to enable heart-beat through the connectFailover settings. The connect object contains connect options that are applied to all the servers in the list.

```js
getConnectFailOverObject() {
    return new stompit.ConnectFailover(['server1','server2','server3'], {
      maxReconnects: 50,
      randomize: true,
      useExponentialBackOff: true,
      connect: {
        connectHeaders: {
          'heart-beat': '5000,5000'
        }
      }
    });
  }
```

**Comment by dakairus** [comment]
Ohhh really thanks for this info, I though the heart beat was enabled of setup by default to certain time.
