### ISSUE TITLE
Durability

### ISSUE THREAD

**Issue by kevintayloruk** [gdaws/node-stomp#50]
Hi,

This is probably my issue and if so I apologise in advance.

I'm trying to connect to ActiveMQ and subscribe to a topic with durability based off of this coed block.

```
const stompit = require('stomp');
 
stompit.connect({ 'client-id': 'SampleClient', host: 'localhost', port: 61613 }, (err, client) => {
    client.subscribe({ 'activemq.subscriptionName': 'SampleSubscription', destination: '/topic/SampleTopic' }, (err, msg) => {
        msg.readString('UTF-8', (err, body) => {
            console.log(body);
 
            client.disconnect();
          });
      });
  });
```

It happily reads the first message sent and disconnects.

If I ...
- send a second message
- connect the client again
- send a third message

...it doesn't receive the second message.

Any thoughts?

Thanks

**Comment by gdaws** [comment]
It sounds like the message broker has failed to make the subscription durable. The communication required to create a durable subscription is made entirely through headers given by the application. Stompit will send all headers (recognised or unknown) to the message broker.

The documentation at [http://activemq.apache.org/stomp.html](http://activemq.apache.org/stomp.html) for ActiveMQ's stomp support says something about needing to use the misspelled header `activemq.subcriptionName` prior to v5.7.0.

In your code snippet there no ack header given in the subscription call, therefore the connection defaults to using auto acknowledgement mode. This mode can cause message loss if the broker sends multiple messages at once to the consumer but then the consumer disconnects after reading the first message.

To avoid this issue use a different ack mode, add `ack: 'client-individual'` to the subscription headers object and then call `client.ack(msg);` in your `msg.readString` callback.
