### ISSUE TITLE
Receive binary content with "0" in bytes

### ISSUE THREAD

**Issue by fxp** [gdaws/node-stomp#51]
I'm trying to send binary data with 0 in the bytes with code:

    var data = new Buffer('lalala');
    data[1]= 0;
    data[0]= 1;
    var frame = client.send(sendHeaders);
    frame.write(data);
    frame.end();

and receive the data with 

    client.subscribe(subscribeHeaders, function (error, message) {
        if (error) {
            console.log('subscribe error ' + error.message);
            return;
        }
        message.on('readable', function (d) {
            console.log('data:', message.read());
        })
        ...

Then it gives me error "Error: Unknown STOMP action: lala"
Is that the right way to send and receive the binary data?

**Comment by gdaws** [comment]
When sending binary data a Content-Length header must be included in the send message.

```js
sendHeaders['content-length'] = buffer.length;
```

The right way to receive data, if you're wanting to process the message after it's been fully received, is to append each readable chunk of the message onto a buffer until the message end event.

```js
message.on('readable', function() {
  buffer = Buffer.concat([buffer, message.read()]);
});

message.on('end', function() {
  // process message
});
```
