### ISSUE TITLE
client.nack(message) invalid

### ISSUE THREAD

**Issue by zhudan** [gdaws/node-stomp#56]
>
![qq20161208-175307](https://cloud.githubusercontent.com/assets/1744697/21005294/33003d16-bd6f-11e6-9d38-95eee288cde8.jpg)
 var subscribeHeaders = {
        'destination': destination,
         'ack': 'client-individual'
        //'ack': 'client'
    };
    var overEvent = function(err, message){
        if(err){
            client.nack(message);
        } else {
            client.nack(message);
        }
    }
    client.subscribe(subscribeHeaders, function(error, message) {
        if (error) {
            logger.error('subscribe error ' + error.message, error);
            return subscribeFailCallback(error, message);
        }
        message.readString('utf-8', function(error, body) {
            if (error) {
                logger.error('read message error ' + error.message, error);
                return overEvent(error, message);
            }
            onMessageCallback(body, function(err){
                overEvent(err, message);
            });
        });
    });

can not nack message!!! it's acked！

**Comment by gdaws** [comment]
Your code is not compatible with `client` ack mode. Use `client-individual` ack mode.

Another thing, don't send a nack message after an error event. The client is dead after any error occurs and thereafter sending any messages to the server will fail.

**Comment by zhudan** [comment]
![qq20161209-161837](https://cloud.githubusercontent.com/assets/1744697/21042242/308cf2ba-be2b-11e6-87b2-dcffb060b3cc.jpg)
![qq20161209-161827 2x](https://cloud.githubusercontent.com/assets/1744697/21042244/338c95d8-be2b-11e6-98f3-f9976193cd39.jpg)


Still the same！
I use activemq with stomp.

**Comment by gdaws** [comment]
It's typical behaviour of a server to dequeue a message after it receives a nack. 

A STOMP client can't enforce what action a server takes when it receives a nack or ack, it depends on what the server software supports and what configuration is in use.

I believe Activemq interprets nack as meaning the message is invalid, and does not attempt to send the message to another subscriber because they too should reply with nack.

**Comment by zhudan** [comment]
but how can nack messsage ?

if process message error，then let's activemq resend with nack message， how to implement this

**Comment by zhudan** [comment]
Found the problem!

nack will be move the message to DLQ.(this message must be Persistence).

**Comment by felimartina** [comment]
@zhudan 
I am facing the same problem. I use ActiveMQ with stompit. Problem I have is that if I `nack` a message it will be removed from the queue (couldn't find the DLQ yet, do you need to setup something for it to show up in ActiveMQ?). But I need the message to persist in the queue and be redelivered. Were you able to achieve such thing?
