### ISSUE TITLE
Defer reading message

### ISSUE THREAD

**Issue by mlucool** [gdaws/node-stomp#61]
Hi,

Looking at the code, it seems to be that I must call `message.readString` synchronously when I get the callback with a message. Instead, I'd like to store the frame and asynchronously read it when I have cycles (e.g. `setTimeout(readMsg, 100)`). Is it possible to defer reading the message or is my reading correct that it either must be consumed or is lost?

Thanks!

**Comment by gdaws** [comment]
There is no requirement to start reading the message within the subscribe callback call.

The `message.readString` function works asynchronously and it doesn't always read the full message in a single read call.

It is possible to defer reading the message, for a short amount of time or indefinitely if STOMP heart-beating is disabled in the incoming direction. But you should be aware that not reading a message you cause the connection to stall by preventing other frames being read and if the application delays reading for too long then it can cause the connection to be dropped.
