### ISSUE TITLE
Leaving the msg on the queue and accessing it later ?

### ISSUE THREAD

**Issue by appsolutegeek** [gdaws/node-stomp#63]
Hi,

I wonder if it's possible to leave the msg on the queue, I have a working example using the sample code. I changed the client.ack to client.nack but my client.subscribe isn't recalled.

Maybe I am missing something ?

As part of my flow, I wanted to reject the msg and leave it in the queue so I can process it later either manually or automatic.

Any ideas how I would achieve this ?

I am using the following

```
    var subscribeHeaders = {
        'destination': destination,
        'ack': 'client-individual'
    };
```

Any help really appreciated.

Thanks

**Comment by gdaws** [comment]
A subscriber replies with a NACK message when it cannot process the received message (now or later), and the message broker typically reacts by discarding the message, moving it to a dead-letter queue or immediately sending it to another subscriber. The exact behaviour of a message broker's NACK handling is different with each implementation and configuration.

How to send a message back to the queue for later consumption?

Define a second queue for storing the delayed messages. The subscriber of the second queue immediately secures and acknowledges a received message and then schedules the message to be re-sent to the first queue when the "later" condition is met.

Whatever the solution is to delayed-message functionality it won't involve the message broker but will likely be implemented as a feature of your application.
