### ISSUE TITLE
ChannelPool doesn't allow to set recoverAfterApplicationError

### ISSUE THREAD

**Issue by afharo** [gdaws/node-stomp#67]
I'd like to set the `recoverAfterApplicationError` flag to `true` for my ChannelPool.

I'm subscribed to AMQ and when there's a reconnection while about to ACK, I get `Unexpected ACK received for message-id [ID:53a45ce8d9b8-35305-1507627714128-1:8:1:1:8]`.
This triggers an applicationError, that, according to the code (https://github.com/gdaws/node-stomp/blob/master/lib/Channel.js#L70) just stops processing (abort) and doesn't re-establish the connection.

By setting this flag to true, the connection is reset and the subscription keeps working as expected.

Right now, I'm using this workaround when getting the channel:
```javascript
return new P((res, rej) => {
      this._channelPool.channel((error, ch) => error ? rej(error) : res(ch));
    })
      .then((channel) => {
        // Needed for the channel to recover when AMQ error happens (typically wrong ACK receipt on reconnection)
        // Assigned like this because ChannelPool doesn't allow sending this parameter in the config (Channel does)
        channel._recoverAfterApplicationError = true;
        return channel;
      });
```

But it doesn't sound right setting internal `_` vars like that.

- Can the ChannelPool class expose this option (I'd rather go for this) or Channel class provide a proper setter for this value?
- Is there any other way to achieve what I want?

Thank you!

**Comment by gdaws** [comment]
Apologies for the delay,

I've gone with your first suggestion and have implemented a way to forward the option through ChannelPool. The ChannelPool constructor now accepts a channelOptions option which is used as the options argument when constructing channels.

Example:
```js
new ChannelPool(connectFailover, { channelOptions: { recoverAfterApplicationError: true } } );
```

**Comment by afharo** [comment]
That sounds great! When will this be published?
