### ISSUE TITLE
Waits to send?

### ISSUE THREAD

**Issue by kevinmlong** [gdaws/node-stomp#78]
Hi - I'm parsing a large number of files and pulling out chunks of text from the files to post to an ActiveMQ broker. I'm looping through the files, getting data using a RegEx.exec, and then looping through the matches to post to the topic. It seems the `stompit` waits to post all the messages until after I'm out of all the loops. Is this expected? Am I doing something wrong? The order of the messages being sent is important. Thanks in advance!

**Comment by gdaws** [comment]
No, stompit doesn't wait to send messages. It sends message as soon as possible, but if too many sends are requested at once it can form a backlog of outgoing messages, and the time it takes to clear the backlog could go on long after the last send call.

So in your scenario, I imagine what happens is the loops run faster than the messages can be sent out.

You don't need to worry about the messages being sent out of order, they will be sent over the connection in the same order as your send calls. You should be more concerned about what impact a backlog of messages has on memory usage.

If you want to prevent growing a message backlog your application needs to respond to the connection's flow control or backpressure. You do this by waiting for the send to finish before doing any further processing.

With stompit you can wait for a sen to finish by listening for the finish event on the frame object (the message being sent).

**Comment by kevinmlong** [comment]
Thanks! Admittedly, I'm new to Node and there were various factors at play here. You're feedback helped - especially the `finish` event. This would be a good thing to add to the docs. I will probably have some additional questions and will open up additional issues for those. Thanks!
