### ISSUE TITLE
Crash Bug: in ./node_modules/stompit/lib/Client.js:360:25

### ISSUE THREAD

**Issue by jikai731** [gdaws/node-stomp#81]
TypeError: this.createProtocolError is not a function
./node_modules/stompit/lib/Client.js:360:25

original:
self.destroy(this.createProtocolError('expected empty body frame'));
Should be：
self.destroy(self.createProtocolError('expected empty body frame'));

**Comment by gdaws** [comment]
Thanks @jikai731 for reporting this bug. Applying the fix now.

**Comment by devdoshicengage** [comment]
Hi, could you publish a release for this? Thanks
