### ISSUE TITLE
error decoding utf-8 string

### ISSUE THREAD

**Issue by crucify** [gdaws/node-stomp#88]
The  code of  IncomingFrame.prototype.readString  is problematic.
For any long utf-8 string with non-ascii characters, it may break the string as one character's utf-8 bytes  be splitted into two parts, one at the first chunk's end and one at the the second chunk's start, resulting 2 unrecognizable characters.

It should use  require('string_decoder').StringDecoder;

 var decoder = new StringDecoder(encoding);
        var read = function () {
            var chunk = readable.read();
            if (chunk !== null) {
                buffer += decoder.write(chunk);
                read();
            }
        };

Please refer to 
https://stackoverflow.com/questions/12121775/convert-streamed-buffers-to-utf8-string
the part about Streamed Buffers with multiple buffer chunks.

**Comment by gdaws** [comment]
Thanks for reporting the issue and providing a fix. 

I've written a test case and indeed readString does not decode a utf-8 string correctly when a multibyte character is received over multiple chunks.
